=== bramstroker/homeassistant-powercalc/profile_library/model_schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "description": "model.json describes a number of devices, typically lights, for use within the HomeAssistant Powercalc extension.",
  "type": "object",
  "required": [
    "name",
    "device_type",
    "measure_method",
    "measure_device",
    "calculation_strategy",
    "created_at"
  ],
  "properties": {
    "aliases": {
      "type": "array",
      "items": {
        "type": "string"
      },
      "description": "Aliases for this model"
    },
    "legacy_ids": {
      "type": "array",
      "items": {
        "type": "string"
      },
      "description": "Legacy canonical model ids which should migrate to this model"
    },
    "compatible_integrations": {
      "type": "array",
      "items": {
        "type": "string"
      },
      "description": "List of compatible integrations for this model"
    },
    "author": {
      "type": "string",
      "deprecated": true
    },
    "author_info": {
      "type": "object",
      "description": "Info about the contributor of the profile",
      "properties": {
        "name": {
          "type": "string",
          "description": "Name of the contributor"
        },
        "email": {
          "type": "string",
          "description": "Email address of the contributor"
        },
        "github": {
          "type": "string",
          "description": "GitHub username of the contributor"
        }
      },
      "required": [
        "name",
        "github"
      ]
    },
    "calculation_enabled_condition": {
      "type": "string",
      "description": "Template which can be evaluated."
    },
    "calculation_strategy": {
      "type": "string",
      "enum": [
        "lut",
        "linear",
        "fixed",
        "multi_switch",
        "composite"
      ],
      "description": "Supported calculation strategies"
    },
    "composite_config": {
      "oneOf": [
        {
          "type": "array",
          "description": "Configuration for composite calculation strategy",
          "items": {
            "type": "object",
            "properties": {
              "condition": {
                "$ref": "#/definitions/condition"
              }
            }
          }
        },
        {
          "type": "object",
          "properties": {
            "mode": {
              "type": "string",
              "enum": [
                "sum_all",
                "stop_at_first"
              ]
            },
            "strategies": {
              "type": "array",
              "description": "Configuration for composite calculation strategy",
              "items": {
                "type": "object",
                "properties": {
                  "condition": {
                    "$ref": "#/definitions/condition"
                  }
                }
              }
            }
          },
          "required": [
            "mode",
            "strategies"
          ]
        }
      ]
    },
    "config_flow_discovery_remarks": {
      "type": "string",
      "description": "Some remarks to show in the GUI config flow on first step of discovery"
    },
    "config_flow_sub_profile_remarks": {
      "type": "string",
      "description": "Some remarks to show in the GUI config flow on sub profile selection step"
    },
    "created_at": {
      "type": "string",
      "format": "date-time",
      "pattern": "^\\d{4}-\\d{2}-\\d{2}T\\d{2}:\\d{2}:\\d{2}Z$",
      "description": "Creation date of the profile"
    },
    "description": {
      "type": "string",
      "description": "A short description of the device"
    },
    "device_type": {
      "type": "string",
      "enum": [
        "camera",
        "cover",
        "fan",
        "generic_iot",
        "light",
        "power_meter",
        "printer",
        "smart_dimmer",
        "smart_switch",
        "smart_speaker",
        "television",
        "network",
        "vacuum_robot",
        "lawn_mower_robot",
        "heating",
        "ups"
      ],
      "description": "Type of device"
    },
    "discovery_by": {
      "type": "string",
      "enum": [
        "device",
        "entity"
      ],
      "description": "Whether to discover the profile by device or entity"
    },
    "fields": {
      "type": "object",
      "additionalProperties": {
        "type": "object",
        "properties": {
          "description": {
            "type": "string",
            "description": "Description of the field"
          },
          "label": {
            "type": "string",
            "description": "Label of the field"
          },
          "selector": {
            "type": "object",
            "properties": {
              "entity": {
                "type": "object",
                "properties": {
                  "domain": {
                    "type": "string"
                  },
                  "device_class": {
                    "type": "string"
                  }
                }
              },
              "number": {
                "type": "object",
                "properties": {
                  "min": {
                    "type": "number"
                  },
                  "max": {
                    "type": "number"
                  }
                }
              }
            }
          }
        }
      }
    },
    "fixed_config": {
      "type": "object",
      "description": "Configuration for fixed calculation strategy",
      "properties": {
        "power": {
          "type": [
            "number",
            "string"
          ]
        },
        "states_power": {
          "type": "object",
          "description": "A dict of state attributes and the power. See https://github.com/bramstroker/homeassistant-powercalc#power-per-state.",
          "properties": {
            "idle": {
              "type": [
                "number",
                "string"
              ]
            },
            "playing": {
              "type": [
                "number",
                "string"
              ]
            },
            "paused": {
              "type": [
                "number",
                "string"
              ]
            },
            "off": {
              "type": [
                "number",
                "string"
              ]
            },
            "unavailable": {
              "type": [
                "number",
                "string"
              ]
            }
          },
          "additionalProperties": {
            "type": [
              "number",
              "string"
            ]
          }
        }
      }
    },
    "is_dumb_bulb": {
      "type": "boolean",
      "description": "The profile is for a dumb light bulb, not having smart capabilities"
    },
    "name": {
      "type": "string",
      "description": "The full name"
    },
    "measure_method": {
      "type": "string",
      "enum": [
        "manual",
        "script"
      ],
      "description": "How the device was measured"
    },
    "measure_description": {
      "type": "string",
      "description": "Add more information about how you measured the device or any remarks"
    },
    "measure_device": {
      "type": "string",
      "description": "Device which was used to measure"
    },
    "measure_device_firmware": {
      "type": "string",
      "description": "Firmware version of the device used to measure"
    },
    "measure_settings": {
      "type": "object",
      "description": "Settings used for measure script"
    },
    "max_voltage": {
      "type": "number",
      "description": "Maximum voltage observed during measurement"
    },
    "min_version": {
      "type": "string",
      "description": "Minimum required version of Powercalc for this profile"
    },
    "min_voltage": {
      "type": "number",
      "description": "Minimum voltage observed during measurement"
    },
    "linear_config": {
      "type": "object",
      "description": "Configuration for linear calculation strategy",
      "properties": {
        "min_power": {
          "type": "number"
        },
        "max_power": {
          "type": "number"
        },
        "calibrate": {
          "type": "array",
          "items": {
            "type": "string"
          }
        }
      }
    },
    "linked_lut": {
      "type": "string",
      "description": "Use LUT data files from another model",
      "deprecated": true
    },
    "linked_profile": {
      "type": "string",
      "description": "Use data from another model"
    },
    "only_self_usage": {
      "type": "boolean",
      "description": "Indicates if profile only provides power usage for the device itself"
    },
    "playbook_config": {
      "type": "object",
      "description": "Configuration for playbook calculation strategy",
      "properties": {
        "playbooks": {
          "type": "object",
          "additionalProperties": {
            "type": "string"
          },
          "description": "Key-value pairs where the key is a playbook ID and the value is the filename."
        },
        "autostart": {
          "type": "string",
          "description": "The playbook ID to autostart."
        },
        "repeat": {
          "type": "boolean",
          "description": "Indicates if the playbook should repeat."
        },
        "state_trigger": {
          "type": "object",
          "additionalProperties": {
            "type": "string"
          },
          "description": "Start given playbook when entity state changes to given value."
        }
      },
      "required": [
        "playbooks"
      ]
    },
    "sensor_config": {
      "type": "object",
      "description": "Sensor configuration options. See the README"
    },
    "standby_power": {
      "type": "number",
      "minimum": 0.05,
      "description": "Power draw when the device is turned off. When you are not able to measure set to 0.4 for lights"
    },
    "standby_power_on": {
      "type": "number",
      "minimum": 0.05,
      "description": "Power draw when the device is turned on."
    },
    "sub_profile_select": {
      "type": "object",
      "description": "Configuration to automatically select a sub profile",
      "required": [
        "default"
      ],
      "properties": {
        "default": {
          "type": "string",
          "description": "Default profile to select when non of the matchers apply"
        },
        "matchers": {
          "type": "array",
          "items": {
            "type": "object",
            "properties": {
              "type": {
                "enum": [
                  "attribute",
                  "entity_id",
                  "entity_registry",
                  "entity_state",
                  "integration",
                  "model_id"
                ]
              },
              "attribute": {
                "type": "string"
              },
              "map": {
                "type": "object"
              },
              "pattern": {
                "type": "string"
              },
              "property": {
                "type": "string"
              },
              "profile": {
                "type": "string"
              },
              "integration": {
                "type": "string"
              },
              "value": {},
              "model_id": {
                "type": "string"
              }
            },
            "required": [
              "type"
            ]
          },
          "description": "List of matchers which will be checked"
        }
      }
    }
  },
  "definitions": {
    "condition": {
      "type": "object",
      "properties": {
        "condition": {
          "type": "string",
          "enum": [
            "and",
            "or",
            "state",
            "numeric_state",
            "template"
          ]
        },
        "conditions": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/condition"
          }
        }
      },
      "additionalProperties": true
    }
  }
}

=== bramstroker/homeassistant-powercalc/profile_library/wiz/SHRGBW/model.json
{
  "calculation_strategy": "lut",
  "created_at": "2022-12-20T18:57:50Z",
  "device_type": "light",
  "measure_description": "Measured 4 bulbs with utils/measure script",
  "measure_device": "TP-Link Kasa HS110",
  "measure_method": "script",
  "measure_settings": {
    "SAMPLE_COUNT": 2,
    "SLEEP_TIME": 5,
    "VERSION": "master"
  },
  "name": "WiZ Bulb A67 E27 RGBWW (type SHRGBW, model 9290024497A, 13 W 220-240 V, 1521 lm)",
  "standby_power": 0.33,
  "author_info": {
    "name": "Jari Eskelinen",
    "email": "jari.eskelinen@iki.fi",
    "github": "jarpatus"
  }
}

=== bramstroker/homeassistant-powercalc/profile_library/homewizard/HWE-SKT/model.json
{
  "aliases": [
    "HWE-SKT",
    "HWE-SKT-21"
  ],
  "author": "Franck Nijhof <opensource@frenck.dev>",
  "calculation_strategy": "fixed",
  "created_at": "2025-03-19T20:30:06",
  "device_type": "smart_switch",
  "measure_description": "Manually measured.",
  "measure_device": "Zhurui PR10-C Power Recorder",
  "measure_method": "manual",
  "name": "HomeWizard Wi-Fi Energy Socket",
  "only_self_usage": true,
  "sensor_config": {
    "energy_sensor_naming": "{} Device Energy",
    "power_sensor_naming": "{} Device Power"
  },
  "standby_power": 0.8,
  "standby_power_on": 1.49
}

=== bramstroker/homeassistant-powercalc/profile_library/eglo/ESMLFzm_w6_Dimm/model.json
{
  "aliases": [
    "ESMLFzm_w6_Dimm"
  ],
  "calculation_strategy": "lut",
  "created_at": "2026-06-01T19:22:09Z",
  "device_type": "light",
  "measure_description": "Measured with utils/measure script",
  "measure_device": "TP-Link Kasa KP115",
  "measure_method": "script",
  "measure_settings": {
    "SAMPLE_COUNT": 5,
    "SLEEP_TIME": 3,
    "VERSION": "master"
  },
  "name": "Eglo connect.z Smart Home E27 LED filament light bulb, G125",
  "standby_power": 0.33
}

=== bramstroker/homeassistant-powercalc/profile_library/lidl/HG06492B/model.json
{
  "calculation_strategy": "lut",
  "created_at": "2022-04-13T17:59:05Z",
  "device_type": "light",
  "measure_description": "Measured with utils/measure script",
  "measure_device": "TP-Link Kasa HS110",
  "measure_method": "script",
  "measure_settings": {
    "SAMPLE_COUNT": 1,
    "SLEEP_TIME": 2,
    "VERSION": "v0.19.5:docker"
  },
  "name": "Livarno Lux E14 candle CCT",
  "standby_power": 0.31,
  "author_info": {
    "name": "Paul Mc Auley",
    "email": "dev@roscarraig.com",
    "github": "roscarraig"
  }
}

=== bramstroker/homeassistant-powercalc/profile_library/gosund/sl2/model.json
{
  "calculation_strategy": "lut",
  "created_at": "2026-01-03T10:49:39Z",
  "device_type": "light",
  "measure_description": "Measured with utils/measure script",
  "measure_device": "Nous A1T",
  "measure_method": "script",
  "measure_settings": {
    "SAMPLE_COUNT": 2,
    "SLEEP_TIME": 3,
    "VERSION": "v1.20.1:docker"
  },
  "name": "Smart Wi-Fi RGB LED Light Strip (5 m)",
  "standby_power": 0.1,
  "author_info": {
    "name": "Jarod2801",
    "github": "Jarod2801"
  }
}

=== bramstroker/homeassistant-powercalc/profile_library/signify/LTP001/model.json
{
  "calculation_strategy": "lut",
  "created_at": "2023-08-20T07:29:54Z",
  "device_type": "light",
  "measure_description": "Measured with utils/measure script",
  "measure_device": "Shelly 1PM",
  "measure_method": "script",
  "measure_settings": {
    "SAMPLE_COUNT": 2,
    "SLEEP_TIME": 2,
    "VERSION": "master"
  },
  "name": "Hue Cher Suspension Light",
  "standby_power": 0.53,
  "author_info": {
    "name": "Nicolas L",
    "github": "Loustik"
  }
}

=== bramstroker/homeassistant-powercalc/profile_library/signify/LWU001/model.json
{
  "aliases": [
    "9290024406"
  ],
  "calculation_strategy": "lut",
  "created_at": "2022-04-04T12:24:27Z",
  "device_type": "light",
  "measure_description": "Measured with utils/measure script",
  "measure_device": "Shelly Plug S",
  "measure_method": "script",
  "measure_settings": {
    "SAMPLE_COUNT": 1,
    "SLEEP_TIME": 2,
    "VERSION": "master"
  },
  "name": "Hue P45 light bulb",
  "standby_power": 0.2,
  "author_info": {
    "name": "Morten Trab",
    "email": "morten@trab.dk",
    "github": "MTrab"
  }
}

=== bramstroker/homeassistant-powercalc/profile_library/linkind/ZBT-DIMLight-D0120/model.json
{
  "calculation_strategy": "lut",
  "created_at": "2023-09-03T13:47:50Z",
  "device_type": "light",
  "measure_description": "Measured with utils/measure script",
  "measure_device": "Shelly Plus Plug S",
  "measure_method": "script",
  "measure_settings": {
    "SAMPLE_COUNT": 2,
    "SLEEP_TIME": 1,
    "VERSION": "v1.9.2:docker"
  },
  "name": "Dimmable Warm White Filament E27 6.2W 806lm Bulb",
  "standby_power": 0.3,
  "author_info": {
    "name": "PalminX",
    "email": "bkuemmer@gmx.net",
    "github": "PalminX"
  }
}
