=== bramstroker/homeassistant-powercalc/profile_library/model_schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "description": "model.json describes a number of devices, typically lights, for use within the HomeAssistant Powercalc extension.",
  "type": "object",
  "required": [
    "name",
    "device_type",
    "measure_method",
    "measure_device",
    "calculation_strategy",
    "created_at"
  ],
  "properties": {
    "aliases": {
      "type": "array",
      "items": {
        "type": "string"
      },
      "description": "Aliases for this model"
    },
    "legacy_ids": {
      "type": "array",
      "items": {
        "type": "string"
      },
      "description": "Legacy canonical model ids which should migrate to this model"
    },
    "compatible_integrations": {
      "type": "array",
      "items": {
        "type": "string"
      },
      "description": "List of compatible integrations for this model"
    },
    "author": {
      "type": "string",
      "deprecated": true
    },
    "author_info": {
      "type": "object",
      "description": "Info about the contributor of the profile",
      "properties": {
        "name": {
          "type": "string",
          "description": "Name of the contributor"
        },
        "email": {
          "type": "string",
          "description": "Email address of the contributor"
        },
        "github": {
          "type": "string",
          "description": "GitHub username of the contributor"
        }
      },
      "required": [
        "name",
        "github"
      ]
    },
    "calculation_enabled_condition": {
      "type": "string",
      "description": "Template which can be evaluated."
    },
    "calculation_strategy": {
      "type": "string",
      "enum": [
        "lut",
        "linear",
        "fixed",
        "multi_switch",
        "composite"
      ],
      "description": "Supported calculation strategies"
    },
    "composite_config": {
      "oneOf": [
        {
          "type": "array",
          "description": "Configuration for composite calculation strategy",
          "items": {
            "type": "object",
            "properties": {
              "condition": {
                "$ref": "#/definitions/condition"
              }
            }
          }
        },
        {
          "type": "object",
          "properties": {
            "mode": {
              "type": "string",
              "enum": [
                "sum_all",
                "stop_at_first"
              ]
            },
            "strategies": {
              "type": "array",
              "description": "Configuration for composite calculation strategy",
              "items": {
                "type": "object",
                "properties": {
                  "condition": {
                    "$ref": "#/definitions/condition"
                  }
                }
              }
            }
          },
          "required": [
            "mode",
            "strategies"
          ]
        }
      ]
    },
    "config_flow_discovery_remarks": {
      "type": "string",
      "description": "Some remarks to show in the GUI config flow on first step of discovery"
    },
    "config_flow_sub_profile_remarks": {
      "type": "string",
      "description": "Some remarks to show in the GUI config flow on sub profile selection step"
    },
    "created_at": {
      "type": "string",
      "format": "date-time",
      "pattern": "^\\d{4}-\\d{2}-\\d{2}T\\d{2}:\\d{2}:\\d{2}Z$",
      "description": "Creation date of the profile"
    },
    "description": {
      "type": "string",
      "description": "A short description of the device"
    },
    "device_type": {
      "type": "string",
      "enum": [
        "camera",
        "cover",
        "fan",
        "generic_iot",
        "light",
        "power_meter",
        "printer",
        "smart_dimmer",
        "smart_switch",
        "smart_speaker",
        "television",
        "network",
        "vacuum_robot",
        "lawn_mower_robot",
        "heating",
        "ups"
      ],
      "description": "Type of device"
    },
    "discovery_by": {
      "type": "string",
      "enum": [
        "device",
        "entity"
      ],
      "description": "Whether to discover the profile by device or entity"
    },
    "fields": {
      "type": "object",
      "additionalProperties": {
        "type": "object",
        "properties": {
          "description": {
            "type": "string",
            "description": "Description of the field"
          },
          "label": {
            "type": "string",
            "description": "Label of the field"
          },
          "selector": {
            "type": "object",
            "properties": {
              "entity": {
                "type": "object",
                "properties": {
                  "domain": {
                    "type": "string"
                  },
                  "device_class": {
                    "type": "string"
                  }
                }
              },
              "number": {
                "type": "object",
                "properties": {
                  "min": {
                    "type": "number"
                  },
                  "max": {
                    "type": "number"
                  }
                }
              }
            }
          }
        }
      }
    },
    "fixed_config": {
      "type": "object",
      "description": "Configuration for fixed calculation strategy",
      "properties": {
        "power": {
          "type": [
            "number",
            "string"
          ]
        },
        "states_power": {
          "type": "object",
          "description": "A dict of state attributes and the power. See https://github.com/bramstroker/homeassistant-powercalc#power-per-state.",
          "properties": {
            "idle": {
              "type": [
                "number",
                "string"
              ]
            },
            "playing": {
              "type": [
                "number",
                "string"
              ]
            },
            "paused": {
              "type": [
                "number",
                "string"
              ]
            },
            "off": {
              "type": [
                "number",
                "string"
              ]
            },
            "unavailable": {
              "type": [
                "number",
                "string"
              ]
            }
          },
          "additionalProperties": {
            "type": [
              "number",
              "string"
            ]
          }
        }
      }
    },
    "is_dumb_bulb": {
      "type": "boolean",
      "description": "The profile is for a dumb light bulb, not having smart capabilities"
    },
    "name": {
      "type": "string",
      "description": "The full name"
    },
    "measure_method": {
      "type": "string",
      "enum": [
        "manual",
        "script"
      ],
      "description": "How the device was measured"
    },
    "measure_description": {
      "type": "string",
      "description": "Add more information about how you measured the device or any remarks"
    },
    "measure_device": {
      "type": "string",
      "description": "Device which was used to measure"
    },
    "measure_device_firmware": {
      "type": "string",
      "description": "Firmware version of the device used to measure"
    },
    "measure_settings": {
      "type": "object",
      "description": "Settings used for measure script"
    },
    "max_voltage": {
      "type": "number",
      "description": "Maximum voltage observed during measurement"
    },
    "min_version": {
      "type": "string",
      "description": "Minimum required version of Powercalc for this profile"
    },
    "min_voltage": {
      "type": "number",
      "description": "Minimum voltage observed during measurement"
    },
    "linear_config": {
      "type": "object",
      "description": "Configuration for linear calculation strategy",
      "properties": {
        "min_power": {
          "type": "number"
        },
        "max_power": {
          "type": "number"
        },
        "calibrate": {
          "type": "array",
          "items": {
            "type": "string"
          }
        }
      }
    },
    "linked_lut": {
      "type": "string",
      "description": "Use LUT data files from another model",
      "deprecated": true
    },
    "linked_profile": {
      "type": "string",
      "description": "Use data from another model"
    },
    "only_self_usage": {
      "type": "boolean",
      "description": "Indicates if profile only provides power usage for the device itself"
    },
    "playbook_config": {
      "type": "object",
      "description": "Configuration for playbook calculation strategy",
      "properties": {
        "playbooks": {
          "type": "object",
          "additionalProperties": {
            "type": "string"
          },
          "description": "Key-value pairs where the key is a playbook ID and the value is the filename."
        },
        "autostart": {
          "type": "string",
          "description": "The playbook ID to autostart."
        },
        "repeat": {
          "type": "boolean",
          "description": "Indicates if the playbook should repeat."
        },
        "state_trigger": {
          "type": "object",
          "additionalProperties": {
            "type": "string"
          },
          "description": "Start given playbook when entity state changes to given value."
        }
      },
      "required": [
        "playbooks"
      ]
    },
    "sensor_config": {
      "type": "object",
      "description": "Sensor configuration options. See the README"
    },
    "standby_power": {
      "type": "number",
      "minimum": 0.05,
      "description": "Power draw when the device is turned off. When you are not able to measure set to 0.4 for lights"
    },
    "standby_power_on": {
      "type": "number",
      "minimum": 0.05,
      "description": "Power draw when the device is turned on."
    },
    "sub_profile_select": {
      "type": "object",
      "description": "Configuration to automatically select a sub profile",
      "required": [
        "default"
      ],
      "properties": {
        "default": {
          "type": "string",
          "description": "Default profile to select when non of the matchers apply"
        },
        "matchers": {
          "type": "array",
          "items": {
            "type": "object",
            "properties": {
              "type": {
                "enum": [
                  "attribute",
                  "entity_id",
                  "entity_registry",
                  "entity_state",
                  "integration",
                  "model_id"
                ]
              },
              "attribute": {
                "type": "string"
              },
              "map": {
                "type": "object"
              },
              "pattern": {
                "type": "string"
              },
              "property": {
                "type": "string"
              },
              "profile": {
                "type": "string"
              },
              "integration": {
                "type": "string"
              },
              "value": {},
              "model_id": {
                "type": "string"
              }
            },
            "required": [
              "type"
            ]
          },
          "description": "List of matchers which will be checked"
        }
      }
    }
  },
  "definitions": {
    "condition": {
      "type": "object",
      "properties": {
        "condition": {
          "type": "string",
          "enum": [
            "and",
            "or",
            "state",
            "numeric_state",
            "template"
          ]
        },
        "conditions": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/condition"
          }
        }
      },
      "additionalProperties": true
    }
  }
}

=== bramstroker/homeassistant-powercalc/profile_library/paulmann licht/500.46/model.json
{
  "calculation_strategy": "lut",
  "created_at": "2025-02-02T20:03:18Z",
  "device_type": "light",
  "measure_description": "Measured with utils/measure script",
  "measure_device": "Shelly PM Mini Gen3",
  "measure_method": "script",
  "measure_settings": {
    "SAMPLE_COUNT": 2,
    "SLEEP_TIME": 3,
    "VERSION": "v1.17.3:docker"
  },
  "name": "Areo VariFit 230mm 2000lm 500.46",
  "standby_power": 0.25,
  "author_info": {
    "name": "metzi",
    "github": "mime24"
  }
}

=== bramstroker/homeassistant-powercalc/profile_library/signify/1743130P7/model.json
{
  "aliases": [
    "1743430P7",
    "1745430P7",
    "9150057310"
  ],
  "calculation_strategy": "lut",
  "created_at": "2022-12-04T08:51:38Z",
  "device_type": "light",
  "linked_profile": "signify/1742930P7",
  "measure_description": "Measured with utils/measure script using OCR",
  "measure_device": "Zhurui PR10",
  "measure_method": "script",
  "name": "Hue Impress Pedestal Low",
  "standby_power": 0.17,
  "author_info": {
    "name": "Cafun",
    "github": "Cafun"
  }
}

=== bramstroker/homeassistant-powercalc/profile_library/yeelight/MJTD01SYL/model.json
{
  "calculation_strategy": "lut",
  "created_at": "2023-02-13T19:22:16Z",
  "device_type": "light",
  "measure_description": "Measured with utils/measure script",
  "measure_device": "Shelly Plug S",
  "measure_method": "script",
  "measure_settings": {
    "SAMPLE_COUNT": 2,
    "SLEEP_TIME": 3,
    "VERSION": "v1.3.4:docker"
  },
  "name": "Mi LED Desk Lamp 1S",
  "standby_power": 0.64,
  "author_info": {
    "name": "Pasquale Cuorpo",
    "github": "maverick1982"
  }
}

=== bramstroker/homeassistant-powercalc/profile_library/shelly/Shelly 1PM/model.json
{
  "aliases": [
    "SHSW-PM"
  ],
  "calculation_strategy": "fixed",
  "created_at": "2024-01-09T19:21:00Z",
  "device_type": "smart_switch",
  "discovery_by": "entity",
  "measure_description": "The measured device fw: 1.14.1-rc1, Eco Mode enabled, Wifi Client enabled, LED disabled. The result represents the average value of measurements collected from the measurement device API for the following scenarios: dumb device/baseline consumption (~4.9W), the the relay turned off, and the relay turned on.",
  "measure_device": "Shelly PM Mini Gen3",
  "measure_device_firmware": "20241011-114503/1.4.4-g6d2a586",
  "measure_method": "manual",
  "measure_settings": {
    "SAMPLE_COUNT": 200,
    "SLEEP_TIME": 0.5
  },
  "name": "1PM",
  "only_self_usage": true,
  "sensor_config": {
    "energy_sensor_naming": "{} Device Energy",
    "power_sensor_naming": "{} Device Power"
  },
  "standby_power": 0.589,
  "standby_power_on": 0.85,
  "author_info": {
    "name": "Michal Bartak",
    "email": "michal.bartak@betsys.com",
    "github": "michalk-k"
  }
}

=== bramstroker/homeassistant-powercalc/profile_library/osram/CLA60 TW/model.json
{
  "aliases": [
    "AC03642"
  ],
  "calculation_strategy": "lut",
  "created_at": "2022-04-24T20:45:34Z",
  "device_type": "light",
  "measure_description": "Measured with utils/measure script",
  "measure_device": "Shelly Plus 1PM",
  "measure_method": "script",
  "measure_settings": {
    "SAMPLE_COUNT": 3,
    "SLEEP_TIME": 2,
    "VERSION": "v0.19.11:docker"
  },
  "name": "SMART+ Classic E27 tunable white",
  "standby_power": 0.5,
  "author_info": {
    "name": "Jan Hoff",
    "github": "mehgrmlhmpf"
  }
}

=== bramstroker/homeassistant-powercalc/profile_library/signify/LLC006/model.json
{
  "aliases": [],
  "calculation_strategy": "lut",
  "created_at": "2022-01-15T15:26:20Z",
  "device_type": "light",
  "measure_description": "Measured with utils/measure script",
  "measure_device": "Shelly Plug S",
  "measure_method": "script",
  "measure_settings": {
    "SAMPLE_COUNT": 1,
    "SLEEP_TIME": 2,
    "VERSION": "v0.14.1"
  },
  "name": "LivingColors Iris Table Lamp Gen3",
  "standby_power": 0.37,
  "author_info": {
    "name": "wormiedk",
    "email": "wormie@alberg.dk",
    "github": "wormiedk"
  }
}

=== bramstroker/homeassistant-powercalc/profile_library/innr/RF 274 T/model.json
{
  "calculation_strategy": "lut",
  "created_at": "2025-12-03T20:49:55Z",
  "device_type": "light",
  "measure_description": "Measured with utils/measure script",
  "measure_device": "Shelly Plug S",
  "measure_method": "script",
  "measure_settings": {
    "SAMPLE_COUNT": 2,
    "SLEEP_TIME": 3,
    "VERSION": "master"
  },
  "name": "Smart Filament Bulb E27 Tunable Edison",
  "standby_power": 0.21,
  "author_info": {
    "name": "Felix",
    "email": "felixsp@posteo.de",
    "github": "felixsp"
  }
}

=== bramstroker/homeassistant-powercalc/profile_library/ikea/E1836/model.json
{
  "aliases": [
    "ASKVADER",
    "On/Off plug (ASKVADER on/off switch)"
  ],
  "author": "confucius78 <dekker.wj@gmail.com>",
  "calculation_strategy": "fixed",
  "created_at": "2023-12-31T20:16:31Z",
  "device_type": "smart_switch",
  "measure_description": "Manually measured.",
  "measure_device": "Shelly Plus Plug S / AVM Fritz!DECT 200",
  "measure_method": "manual",
  "name": "ASKVADER on/off switch",
  "only_self_usage": false,
  "standby_power": 0.21,
  "standby_power_on": 0.78,
  "author_info": {
    "name": "confucius78",
    "email": "dekker.wj@gmail.com",
    "github": "confucius78"
  }
}
