=== bramstroker/homeassistant-powercalc/profile_library/model_schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "description": "model.json describes a number of devices, typically lights, for use within the HomeAssistant Powercalc extension.",
  "type": "object",
  "required": [
    "name",
    "device_type",
    "measure_method",
    "measure_device",
    "calculation_strategy",
    "created_at"
  ],
  "properties": {
    "aliases": {
      "type": "array",
      "items": {
        "type": "string"
      },
      "description": "Aliases for this model"
    },
    "legacy_ids": {
      "type": "array",
      "items": {
        "type": "string"
      },
      "description": "Legacy canonical model ids which should migrate to this model"
    },
    "compatible_integrations": {
      "type": "array",
      "items": {
        "type": "string"
      },
      "description": "List of compatible integrations for this model"
    },
    "author": {
      "type": "string",
      "deprecated": true
    },
    "author_info": {
      "type": "object",
      "description": "Info about the contributor of the profile",
      "properties": {
        "name": {
          "type": "string",
          "description": "Name of the contributor"
        },
        "email": {
          "type": "string",
          "description": "Email address of the contributor"
        },
        "github": {
          "type": "string",
          "description": "GitHub username of the contributor"
        }
      },
      "required": [
        "name",
        "github"
      ]
    },
    "calculation_enabled_condition": {
      "type": "string",
      "description": "Template which can be evaluated."
    },
    "calculation_strategy": {
      "type": "string",
      "enum": [
        "lut",
        "linear",
        "fixed",
        "multi_switch",
        "composite"
      ],
      "description": "Supported calculation strategies"
    },
    "composite_config": {
      "oneOf": [
        {
          "type": "array",
          "description": "Configuration for composite calculation strategy",
          "items": {
            "type": "object",
            "properties": {
              "condition": {
                "$ref": "#/definitions/condition"
              }
            }
          }
        },
        {
          "type": "object",
          "properties": {
            "mode": {
              "type": "string",
              "enum": [
                "sum_all",
                "stop_at_first"
              ]
            },
            "strategies": {
              "type": "array",
              "description": "Configuration for composite calculation strategy",
              "items": {
                "type": "object",
                "properties": {
                  "condition": {
                    "$ref": "#/definitions/condition"
                  }
                }
              }
            }
          },
          "required": [
            "mode",
            "strategies"
          ]
        }
      ]
    },
    "config_flow_discovery_remarks": {
      "type": "string",
      "description": "Some remarks to show in the GUI config flow on first step of discovery"
    },
    "config_flow_sub_profile_remarks": {
      "type": "string",
      "description": "Some remarks to show in the GUI config flow on sub profile selection step"
    },
    "created_at": {
      "type": "string",
      "format": "date-time",
      "pattern": "^\\d{4}-\\d{2}-\\d{2}T\\d{2}:\\d{2}:\\d{2}Z$",
      "description": "Creation date of the profile"
    },
    "description": {
      "type": "string",
      "description": "A short description of the device"
    },
    "device_type": {
      "type": "string",
      "enum": [
        "camera",
        "cover",
        "fan",
        "generic_iot",
        "light",
        "power_meter",
        "printer",
        "smart_dimmer",
        "smart_switch",
        "smart_speaker",
        "television",
        "network",
        "vacuum_robot",
        "lawn_mower_robot",
        "heating",
        "ups"
      ],
      "description": "Type of device"
    },
    "discovery_by": {
      "type": "string",
      "enum": [
        "device",
        "entity"
      ],
      "description": "Whether to discover the profile by device or entity"
    },
    "fields": {
      "type": "object",
      "additionalProperties": {
        "type": "object",
        "properties": {
          "description": {
            "type": "string",
            "description": "Description of the field"
          },
          "label": {
            "type": "string",
            "description": "Label of the field"
          },
          "selector": {
            "type": "object",
            "properties": {
              "entity": {
                "type": "object",
                "properties": {
                  "domain": {
                    "type": "string"
                  },
                  "device_class": {
                    "type": "string"
                  }
                }
              },
              "number": {
                "type": "object",
                "properties": {
                  "min": {
                    "type": "number"
                  },
                  "max": {
                    "type": "number"
                  }
                }
              }
            }
          }
        }
      }
    },
    "fixed_config": {
      "type": "object",
      "description": "Configuration for fixed calculation strategy",
      "properties": {
        "power": {
          "type": [
            "number",
            "string"
          ]
        },
        "states_power": {
          "type": "object",
          "description": "A dict of state attributes and the power. See https://github.com/bramstroker/homeassistant-powercalc#power-per-state.",
          "properties": {
            "idle": {
              "type": [
                "number",
                "string"
              ]
            },
            "playing": {
              "type": [
                "number",
                "string"
              ]
            },
            "paused": {
              "type": [
                "number",
                "string"
              ]
            },
            "off": {
              "type": [
                "number",
                "string"
              ]
            },
            "unavailable": {
              "type": [
                "number",
                "string"
              ]
            }
          },
          "additionalProperties": {
            "type": [
              "number",
              "string"
            ]
          }
        }
      }
    },
    "is_dumb_bulb": {
      "type": "boolean",
      "description": "The profile is for a dumb light bulb, not having smart capabilities"
    },
    "name": {
      "type": "string",
      "description": "The full name"
    },
    "measure_method": {
      "type": "string",
      "enum": [
        "manual",
        "script"
      ],
      "description": "How the device was measured"
    },
    "measure_description": {
      "type": "string",
      "description": "Add more information about how you measured the device or any remarks"
    },
    "measure_device": {
      "type": "string",
      "description": "Device which was used to measure"
    },
    "measure_device_firmware": {
      "type": "string",
      "description": "Firmware version of the device used to measure"
    },
    "measure_settings": {
      "type": "object",
      "description": "Settings used for measure script"
    },
    "max_voltage": {
      "type": "number",
      "description": "Maximum voltage observed during measurement"
    },
    "min_version": {
      "type": "string",
      "description": "Minimum required version of Powercalc for this profile"
    },
    "min_voltage": {
      "type": "number",
      "description": "Minimum voltage observed during measurement"
    },
    "linear_config": {
      "type": "object",
      "description": "Configuration for linear calculation strategy",
      "properties": {
        "min_power": {
          "type": "number"
        },
        "max_power": {
          "type": "number"
        },
        "calibrate": {
          "type": "array",
          "items": {
            "type": "string"
          }
        }
      }
    },
    "linked_lut": {
      "type": "string",
      "description": "Use LUT data files from another model",
      "deprecated": true
    },
    "linked_profile": {
      "type": "string",
      "description": "Use data from another model"
    },
    "only_self_usage": {
      "type": "boolean",
      "description": "Indicates if profile only provides power usage for the device itself"
    },
    "playbook_config": {
      "type": "object",
      "description": "Configuration for playbook calculation strategy",
      "properties": {
        "playbooks": {
          "type": "object",
          "additionalProperties": {
            "type": "string"
          },
          "description": "Key-value pairs where the key is a playbook ID and the value is the filename."
        },
        "autostart": {
          "type": "string",
          "description": "The playbook ID to autostart."
        },
        "repeat": {
          "type": "boolean",
          "description": "Indicates if the playbook should repeat."
        },
        "state_trigger": {
          "type": "object",
          "additionalProperties": {
            "type": "string"
          },
          "description": "Start given playbook when entity state changes to given value."
        }
      },
      "required": [
        "playbooks"
      ]
    },
    "sensor_config": {
      "type": "object",
      "description": "Sensor configuration options. See the README"
    },
    "standby_power": {
      "type": "number",
      "minimum": 0.05,
      "description": "Power draw when the device is turned off. When you are not able to measure set to 0.4 for lights"
    },
    "standby_power_on": {
      "type": "number",
      "minimum": 0.05,
      "description": "Power draw when the device is turned on."
    },
    "sub_profile_select": {
      "type": "object",
      "description": "Configuration to automatically select a sub profile",
      "required": [
        "default"
      ],
      "properties": {
        "default": {
          "type": "string",
          "description": "Default profile to select when non of the matchers apply"
        },
        "matchers": {
          "type": "array",
          "items": {
            "type": "object",
            "properties": {
              "type": {
                "enum": [
                  "attribute",
                  "entity_id",
                  "entity_registry",
                  "entity_state",
                  "integration",
                  "model_id"
                ]
              },
              "attribute": {
                "type": "string"
              },
              "map": {
                "type": "object"
              },
              "pattern": {
                "type": "string"
              },
              "property": {
                "type": "string"
              },
              "profile": {
                "type": "string"
              },
              "integration": {
                "type": "string"
              },
              "value": {},
              "model_id": {
                "type": "string"
              }
            },
            "required": [
              "type"
            ]
          },
          "description": "List of matchers which will be checked"
        }
      }
    }
  },
  "definitions": {
    "condition": {
      "type": "object",
      "properties": {
        "condition": {
          "type": "string",
          "enum": [
            "and",
            "or",
            "state",
            "numeric_state",
            "template"
          ]
        },
        "conditions": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/condition"
          }
        }
      },
      "additionalProperties": true
    }
  }
}

=== bramstroker/homeassistant-powercalc/profile_library/signify/929004297401/model.json
{
  "aliases": [
    "929004297401"
  ],
  "calculation_strategy": "lut",
  "created_at": "2025-11-04T00:15:59Z",
  "device_type": "light",
  "measure_description": "Measured with utils/measure script",
  "measure_device": "Shelly PM Mini Gen3",
  "measure_method": "script",
  "measure_settings": {
    "SAMPLE_COUNT": 2,
    "SLEEP_TIME": 2,
    "VERSION": "v1.17.24:docker"
  },
  "name": "Hue Devote Slim ceiling light (29cm)",
  "standby_power": 0.18,
  "author_info": {
    "name": "Tom Frenzel",
    "email": "admin@tom-frenzel.de",
    "github": "tomfrenzel"
  }
}

=== bramstroker/homeassistant-powercalc/profile_library/signify/915005997501/model.json
{
  "aliases": [
    "9150059975"
  ],
  "calculation_strategy": "lut",
  "created_at": "2023-02-28T18:32:53Z",
  "device_type": "light",
  "measure_description": "Measured with utils/measure script",
  "measure_device": "Shelly 1PM",
  "measure_method": "script",
  "measure_settings": {
    "SAMPLE_COUNT": 2,
    "SLEEP_TIME": 3,
    "VERSION": "master"
  },
  "name": "Hue Infuse Large Ceiling Lamp",
  "standby_power": 0.34,
  "author_info": {
    "name": "matteobreschig",
    "github": "matteobreschig"
  }
}

=== bramstroker/homeassistant-powercalc/profile_library/sonos/playbar/model.json
{
  "aliases": [
    "Playbar"
  ],
  "calculation_enabled_condition": "{{ is_state('[[entity]]', 'playing') }}",
  "calculation_strategy": "linear",
  "created_at": "2023-04-14T16:03:13Z",
  "device_type": "smart_speaker",
  "linear_config": {
    "calibrate": [
      "0 -> 10.00",
      "10 -> 10.10",
      "20 -> 10.10",
      "30 -> 10.10",
      "40 -> 10.10",
      "50 -> 10.20",
      "60 -> 10.70",
      "70 -> 11.80",
      "80 -> 15.80",
      "90 -> 26.10",
      "100 -> 26.90"
    ]
  },
  "measure_description": "Streamed 'Pink noise' from https://www.genelec.com/audio-test-signals and measured using HAOS; manual mute/zero volume measurement.",
  "measure_device": "ZOOZ Z-WAVE PLUS S2 POWER STRIP ZEN20 VER. 3.0",
  "measure_method": "script",
  "name": "Playbar",
  "standby_power": 5.2,
  "author_info": {
    "name": "alvinchen1",
    "github": "alvinchen1"
  }
}

=== bramstroker/homeassistant-powercalc/profile_library/shelly/Shelly Plus Plug US/model.json
{
  "aliases": [
    "SNPL-00116US"
  ],
  "calculation_strategy": "lut",
  "created_at": "2025-07-15T04:34:00Z",
  "device_type": "smart_switch",
  "discovery_by": "entity",
  "linked_profile": "shelly/shelly plus plug s",
  "measure_description": "Measured with an Aeotec ZWA023 and seems to align with (more precise) measurements from Shelly Plus Plug S.",
  "measure_device": "Aeotec ZWA023",
  "measure_method": "script",
  "name": "Plus Plug US",
  "author_info": {
    "name": "Josh Barnard",
    "github": "barndawgie"
  }
}

=== bramstroker/homeassistant-powercalc/profile_library/apple/HomePod Mini/model.json
{
  "calculation_enabled_condition": "{{ is_state('[[entity]]', 'playing') }}",
  "calculation_strategy": "linear",
  "config_flow_discovery_remarks": "**Warning**, please verify this device is a single speaker and not part of a stereo or Home theater configuration. This powercalc profile is specifically for a single speaker, so when you accept it anyway power estimation will be way off. When this is the case for you please ignore this discovery by clicking the three dots and ignore.",
  "created_at": "2023-04-03T20:55:15Z",
  "device_type": "smart_speaker",
  "linear_config": {
    "calibrate": [
      "0 -> 0.99",
      "10 -> 1.02",
      "20 -> 1.03",
      "30 -> 1.04",
      "40 -> 1.05",
      "50 -> 1.06",
      "60 -> 1.33",
      "70 -> 1.92",
      "80 -> 2.18",
      "90 -> 2.77",
      "100 -> 4.22"
    ]
  },
  "measure_description": "Streamed white noise for this test",
  "measure_device": "Shelly Plug S",
  "measure_method": "manual",
  "name": "HomePod Mini",
  "standby_power": 0.65,
  "author_info": {
    "name": "vandalon",
    "email": "joris@vandalon.nl",
    "github": "vandalon"
  }
}

=== bramstroker/homeassistant-powercalc/profile_library/meross/msl120d 2.0.0/model.json
{
  "calculation_strategy": "lut",
  "created_at": "2022-09-26T21:02:13Z",
  "device_type": "light",
  "measure_description": "Measured with utils/measure script",
  "measure_device": "TP-Link Tapo P110",
  "measure_method": "script",
  "measure_settings": {
    "SAMPLE_COUNT": 2,
    "SLEEP_TIME": 3,
    "VERSION": "v0.25.5:docker"
  },
  "name": "Smart Wi-Fi LED Bulb",
  "standby_power": 0.56,
  "author_info": {
    "name": "Joshua Rich",
    "email": "joshua.rich@gmail.com",
    "github": "joshuar"
  }
}

=== bramstroker/homeassistant-powercalc/profile_library/govee/H60A1/model.json
{
  "calculation_strategy": "lut",
  "created_at": "2025-12-29T22:45:08Z",
  "device_type": "light",
  "measure_description": "Measured with utils/measure script",
  "measure_device": "Shelly 1PM Mini Gen4",
  "measure_method": "script",
  "measure_settings": {
    "SAMPLE_COUNT": 2,
    "SLEEP_TIME": 3,
    "VERSION": "v1.20.0:docker"
  },
  "name": "Smart Ceiling Light",
  "standby_power": 0.45,
  "author_info": {
    "name": "gobbli",
    "github": "gobbli"
  }
}

=== bramstroker/homeassistant-powercalc/profile_library/signify/LWA009/model.json
{
  "aliases": [
    "9290023349"
  ],
  "calculation_strategy": "lut",
  "created_at": "2021-08-21T07:43:16Z",
  "device_type": "light",
  "measure_description": "Measured twice with script made by bramstroker using 9 sec pauses and partially verified manual",
  "measure_device": "Shelly Plug S",
  "measure_method": "script",
  "name": "Hue White Bulb A67 E27 1600lm",
  "standby_power": 0.41,
  "author_info": {
    "name": "nepozs",
    "email": "szopen@os.pl",
    "github": "nepozs"
  }
}
