=== bramstroker/homeassistant-powercalc/custom_components/powercalc/data/model_schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "description": "model.json describes a number of devices, typically lights, for use within the HomeAssistant Powercalc extension.",
  "type": "object",
  "required": [
    "name",
    "standby_power",
    "measure_method",
    "measure_device",
    "supported_modes"
  ],
  "properties": {
    "name": {
      "type": "string",
      "description": "The full name"
    },
    "standby_power": {
      "type": "number",
      "minimum": 0.05,
      "description": "Power draw when the device is turned off. When you are not able to measure set to 0.4 for lights"
    },
    "standby_power_on": {
      "type": "number",
      "minimum": 0.05,
      "description": "Power draw when the device is turned on."
    },
    "supported_modes": {
      "type": "array",
      "minItems": 1,
      "items": {
        "type": "string",
        "enum": ["lut", "linear", "fixed"]
      },
      "description": "Supported calculation modes"
    },
    "measure_method": {
      "type": "string",
      "enum": ["manual", "script"],
      "description": "How the device was measured"
    },
    "measure_device": {
      "type": "string",
      "description": "Device which was used to measure"
    },
    "measure_description": {
      "type": "string",
      "description": "Add more information about how you measured the device or any remarks"
    },
    "measure_settings": {
      "type": "object",
      "description": "Settings used for measure script"
    },
    "linked_lut": {
      "type": "string",
      "description": "Use LUT data files from another model"
    },
    "requires_additional_configuration": {
      "type": "boolean",
      "description": "Defines whether this model needs additional configuration by the user. Used for smart switches and lights where we can only know the standby power, but not the power of connected light bulb"
    },
    "device_type": {
      "type": "string",
      "enum": ["light", "smart_switch"],
      "description": "Type of device"
    },
    "calculation_enabled_condition": {
      "type": "string",
      "description": "Template which can be evaluated."
    },
    "aliases": {
      "type": "array",
      "items": {
        "type": "string"
      },
      "description": "Aliases for this model"
    },
    "linear_config": {
      "type": "object",
      "description": "Configuration for linear calculation mode",
      "properties": {
        "min_watt": {
          "type": "number"
        },
        "max_watt": {
          "type": "number"
        }
      }
    },
    "fixed_config": {
      "type": "object",
      "description": "Configuration for fixed calculation mode",
      "properties": {
        "watt": {
          "type": "number"
        }
      }
    },
    "sensor_config": {
      "type": "object",
      "description": "Sensor configuration options. See the README"
    }
  }
}

=== bramstroker/homeassistant-powercalc/custom_components/powercalc/data/signify/LCA003/model.json
{
    "measure_description": "Measured with utils/measure script.  Controller: hue, Bulbs: 3, Dummy Load: None",
    "measure_device": "Kasa, KP115(US)",
    "measure_method": "script",
    "measure_settings": {
        "SAMPLE_COUNT": 2,
        "SLEEP_TIME": 3,
        "VERSION": "v0.24.8:docker"
    },
    "name": "Hue White and Color Ambiance A19 E26",
    "standby_power": 0.17,
    "supported_modes": [
        "lut"
    ]
}

=== bramstroker/homeassistant-powercalc/custom_components/powercalc/data/lidl/HG06492B/model.json
{
    "measure_description": "Measured with utils/measure script",
    "measure_device": "Kasa HS110",
    "measure_method": "script",
    "measure_settings": {
        "SAMPLE_COUNT": 1,
        "SLEEP_TIME": 2,
        "VERSION": "v0.19.5:docker"
    },
    "name": "Livarno Lux E14 candle CCT",
    "standby_power": 0.31,
    "supported_modes": [
        "lut"
    ]
}

=== bramstroker/homeassistant-powercalc/custom_components/powercalc/data/signify/LWA005/model.json
{
    "measure_description": "Measured with utils/measure script",
    "measure_device": "Sonoff, S31",
    "measure_method": "script",
    "measure_settings": {
        "SAMPLE_COUNT": 7,
        "SLEEP_TIME": 15,
        "VERSION": "v0.19.15:docker"
    },
    "name": "Hue Filament E26",
    "standby_power": 0.11,
    "supported_modes": [
        "lut"
    ],
    "aliases": []
}

=== bramstroker/homeassistant-powercalc/custom_components/powercalc/data/ikea/LED1736G9/model.json
{
    "measure_description": "Measured with utils/measure script",
    "measure_device": "Shelly, 1PM",
    "measure_method": "script",
    "measure_settings": {
        "SAMPLE_COUNT": 1,
        "SLEEP_TIME": 2,
        "VERSION": "v0.13.4"
    },
    "name": "TRADFRI bulb E27 WS clear 806lm",
    "standby_power": 0.34,
    "supported_modes": [
        "lut"
    ],
    "aliases": [
        "TRADFRI bulb E27 WS clear 806lm"
    ]
}

=== bramstroker/homeassistant-powercalc/custom_components/powercalc/data/ikea/LED2003G10/model.json
{
    "measure_description": "Measured with utils/measure script",
    "measure_device": "Shelly Plug S",
    "measure_method": "script",
    "measure_settings": {
        "SAMPLE_COUNT": 3,
        "SLEEP_TIME": 6,
        "VERSION": "master"
    },
    "name": "TRADFRI LED bulb E27 1055 lumen, dimmable, white spectrum, opal white",
    "standby_power": 0.17,
    "supported_modes": [
        "lut"
    ],
    "aliases": [
        "TRADFRIbulbE27WSglobeopal1055lm"
    ]
}

=== bramstroker/homeassistant-powercalc/custom_components/powercalc/data/signify/LWO002/model.json
{
    "measure_device": "Shelly Plug S",
    "measure_method": "script",
    "measure_description": "Measured with utils/measure, SAMPLE_COUNT=3",
    "name": "Hue White G25 E26 Edison Filament Globe Bluetooth",
    "standby_power": 0.35,
    "supported_modes": [
        "lut"
    ],
    "linked_lut": "signify/LWO001"
}

=== bramstroker/homeassistant-powercalc/custom_components/powercalc/data/yeelight/YLDP06YL/model.json
{
    "measure_description": "Measured with utils/measure script",
    "measure_device": "Kasa KP115",
    "measure_method": "script",
    "measure_settings": {
        "SAMPLE_COUNT": 1,
        "SLEEP_TIME": 10,
        "VERSION": "v0.19.7"
    },
    "name": "Yeelight Smart LED Bulb II Color",
    "standby_power": 1.07,
    "supported_modes": [
        "lut"
    ],
    "aliases": [
        "color2"
    ]
}
