=== bramstroker/homeassistant-powercalc/custom_components/powercalc/data/model_schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "description": "model.json describes a number of devices, typically lights, for use within the HomeAssistant Powercalc extension.",
  "type": "object",
  "required": [
    "name",
    "standby_power",
    "measure_method",
    "measure_device",
    "supported_modes"
  ],
  "properties": {
    "name": {
      "type": "string",
      "description": "The full name"
    },
    "standby_power": {
      "type": "number",
      "minimum": 0.05,
      "description": "Power draw when the device is turned off. When you are not able to measure set to 0.4 for lights"
    },
    "standby_power_on": {
      "type": "number",
      "minimum": 0.05,
      "description": "Power draw when the device is turned on."
    },
    "supported_modes": {
      "type": "array",
      "minItems": 1,
      "items": {
        "type": "string",
        "enum": ["lut", "linear", "fixed"]
      },
      "description": "Supported calculation modes"
    },
    "measure_method": {
      "type": "string",
      "enum": ["manual", "script"],
      "description": "How the device was measured"
    },
    "measure_device": {
      "type": "string",
      "description": "Device which was used to measure"
    },
    "measure_description": {
      "type": "string",
      "description": "Add more information about how you measured the device or any remarks"
    },
    "measure_settings": {
      "type": "object",
      "description": "Settings used for measure script"
    },
    "linked_lut": {
      "type": "string",
      "description": "Use LUT data files from another model"
    },
    "requires_additional_configuration": {
      "type": "boolean",
      "description": "Defines whether this model needs additional configuration by the user. Used for smart switches and lights where we can only know the standby power, but not the power of connected light bulb"
    },
    "device_type": {
      "type": "string",
      "enum": ["light", "smart_switch"],
      "description": "Type of device"
    },
    "calculation_enabled_condition": {
      "type": "string",
      "description": "Template which can be evaluated."
    },
    "aliases": {
      "type": "array",
      "items": {
        "type": "string"
      },
      "description": "Aliases for this model"
    },
    "linear_config": {
      "type": "object",
      "description": "Configuration for linear calculation mode",
      "properties": {
        "min_watt": {
          "type": "number"
        },
        "max_watt": {
          "type": "number"
        }
      }
    },
    "fixed_config": {
      "type": "object",
      "description": "Configuration for fixed calculation mode",
      "properties": {
        "watt": {
          "type": "number"
        }
      }
    },
    "sensor_config": {
      "type": "object",
      "description": "Sensor configuration options. See the README"
    }
  }
}

=== bramstroker/homeassistant-powercalc/custom_components/powercalc/data/tuya/SL20/model.json
{
    "measure_description": "Measured with utils/measure script",
    "measure_device": "Sonoff S31",
    "measure_method": "script",
    "measure_settings": {
        "SAMPLE_COUNT": 3,
        "SLEEP_TIME": 5,
        "VERSION": "master"
    },
    "name": "Treatlife SL20",
    "standby_power": 0.1,
    "supported_modes": [
        "lut"
    ]
}

=== bramstroker/homeassistant-powercalc/custom_components/powercalc/data/lifx/LIFX BR30 Night Vision/model.json
{
    "measure_description": "Measured with utils/measure script",
    "measure_device": "Kasa KP115",
    "measure_method": "script",
    "measure_settings": {
        "SAMPLE_COUNT": 1,
        "SLEEP_TIME": 1,
        "VERSION": "v0.17.0:docker"
    },
    "name": "LIFX BR30 Night Vision",
    "standby_power": 0.72,
    "supported_modes": [
        "lut"
    ]
}

=== bramstroker/homeassistant-powercalc/custom_components/powercalc/data/innr/RS 125/model.json
{
    "name": "RS125 GU10 350lm 2700K",
    "standby_power": 0.38,
    "supported_modes": [
        "lut"
    ],
    "measure_method": "manual",
    "measure_device": "Power Recorder; PR10-D (Model); Shenzen Zhurui Technology (Manufacturer)",
    "measure_description": "Bulbs was measured twice at each dim setting (100 points) and mean value was used when there were differences"
}

=== bramstroker/homeassistant-powercalc/custom_components/powercalc/data/signify/LTP008/model.json
{
    "measure_description": "Measured with utils/measure script",
    "measure_device": "Shelly Plug S",
    "measure_method": "script",
    "measure_settings": {
        "SAMPLE_COUNT": 1,
        "SLEEP_TIME": 2,
        "VERSION": "v0.18.4:docker"
    },
    "name": "Hue Being Pendant Light",
    "standby_power": 0.38,
    "supported_modes": [
        "lut"
    ],
    "aliases": []
}

=== bramstroker/homeassistant-powercalc/custom_components/powercalc/data/innr/SP 224/model.json
{
	"measure_description": "Manually measured w/3.65W Incandescent nightlight.",
	"measure_method": "manual",
	"measure_device": "Kasa KP115(US)",
	"name": "Innr Zigbee Smart Plug",
	"standby_power": 0.18,
	"sensor_config": {
		"power_sensor_naming": "{} Device Power",
		"energy_sensor_naming": "{} Device Energy"
  	},
	"device_type": "smart_switch",
	"supported_modes": [
		"fixed"
	],
	"fixed_config": {
		"power": 0.83
	}
}

=== bramstroker/homeassistant-powercalc/custom_components/powercalc/data/wiz/9290022662/model.json
{
    "measure_description": "Measured 3 bulbs with utils/measure script with no dummy load",
    "measure_device": "Kasa KP115",
    "measure_method": "script",
    "measure_settings": {
        "SAMPLE_COUNT": 2,
        "SLEEP_TIME": 5,
        "VERSION": "master"
    },
    "name": "Wiz Filament ST19 E26 Transparent (type SHDW9, model 9290022662, 3.8W 120V)",
    "standby_power": 0.38,
    "supported_modes": [
        "lut"
    ]
}

=== bramstroker/homeassistant-powercalc/custom_components/powercalc/data/elgato/elgato key light air/model.json
{
    "measure_description": "Measured with utils/measure script",
    "measure_device": "Shelly Plug S",
    "measure_method": "script",
    "measure_settings": {
        "SAMPLE_COUNT": 2,
        "SLEEP_TIME": 3,
        "VERSION": "master"
    },
    "name": "Elgato Key Light Air",
    "standby_power": 0.41,
    "supported_modes": [
        "lut"
    ]
}

=== bramstroker/homeassistant-powercalc/custom_components/powercalc/data/signify/LTW010/model.json
{
    "name": "Hue White Ambiance A60 E27 806lm 9290012001A",
    "standby_power": 0.39,
    "supported_modes": [
        "lut"
    ],
    "measure_method": "script",
    "measure_device": "Shelly Plug S",
    "measure_description": "Measured with script made by bramstroker and partially verified manual"
}
